### ISSUE TITLE
cdk bootstrap fails because of "TSError: ⨯ Unable to compile TypeScript"

### ISSUE THREAD

**Issue by a455bcd9** [a5an0/ThunderCloud#4]
When I do `cdk bootstrap` I get the following error:

```
/ThunderCloud/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/lightningnode-stack.ts:77:28 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'LightningNode' is not assignable to type 'Construct'.
    Types of property 'node' are incompatible.
      Type 'import("/ThunderCloud/node_modules/@aws-cdk/core/lib/construct-compat").ConstructNode' is not assignable to type 'import("/ThunderCloud/node_modules/@aws-cdk/aws-iam/node_modules/@aws-cdk/core/lib/construct-compat").ConstructNode'.
        Types have separate declarations of a private property 'host'.

77     const eip = new CfnEIP(this, "NodeEIP" + suffix, {
                              ~~~~

    at createTSError (/ThunderCloud/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/ThunderCloud/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/ThunderCloud/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/ThunderCloud/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/ThunderCloud/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/ThunderCloud/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
Subprocess exited with error 1
```

Some information about my environment:

- `node -v`: "v16.8.0"
- `tsc -v`: "Version 4.4.2"

Any idea what to do to solve this?

**Comment by a5an0** [comment]
Looks like it's an npm issue. I added a package-lock. Pull the latest rev, do `npm install` and try again. let me know if it works or not.

**Comment by a455bcd9** [comment]
Sorry for the late reply. Thanks a lot: problem solved!
